<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir).'/wp_ib_directory';

return array(
    'WPMVC\\PHPFastCache\\' => array($vendorDir . '/10quality/wpmvc-phpfastcache/src/psr4'),
    'WPMVC\\MVC\\' => array($vendorDir . '/10quality/wpmvc-mvc/src'),
    'WPMVC\\KLogger\\' => array($vendorDir . '/10quality/wpmvc-logger/src'),
    'WPMVC\\Commands\\' => array($vendorDir . '/10quality/wpmvc-commands/src'),
    'WPMVC\\' => array($vendorDir . '/10quality/wpmvc-core/src/psr4'),
    'TenQuality\\WP\\' => array($vendorDir . '/10quality/wp-file/src'),
    'TenQuality\\Gettext\\Scanner\\' => array($vendorDir . '/10quality/gettext-wp-scanner/src'),
    'PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'Peast\\' => array($vendorDir . '/mck89/peast/lib/Peast'),
    'PHP_Parallel_Lint\\PhpConsoleColor\\' => array($vendorDir . '/php-parallel-lint/php-console-color/src'),
    'IB\\directory\\' => array($baseDir . '/app'),
    'Gettext\\Scanner\\' => array($vendorDir . '/gettext/php-scanner/src', $vendorDir . '/gettext/js-scanner/src'),
    'Gettext\\Languages\\' => array($vendorDir . '/gettext/languages/src'),
    'Gettext\\' => array($vendorDir . '/gettext/gettext/src'),
    'DiDom\\' => array($vendorDir . '/imangazaliev/didom/src/DiDom'),
    'Ayuco\\' => array($vendorDir . '/10quality/ayuco/src'),
);
