<?php return array(
    'root' => array(
        'name' => '10quality/wpmvc',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '375a4c43ea54de58b8e767afc925ca477396b4cf',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../wp_ib_directory',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '10quality/ayuco' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => '7ccc56bfae47dcc3dba6f257a2ce5b2aa40f744a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/ayuco',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        '10quality/gettext-wp-scanner' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f2109db81b952e411ebbce88a8bd8c28054eda3a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/gettext-wp-scanner',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        '10quality/wp-file' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '6bfb7de165082e06c82462532768cc7ae7fc4b4e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wp-file',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '375a4c43ea54de58b8e767afc925ca477396b4cf',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../wp_ib_directory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc-commands' => array(
            'pretty_version' => 'v1.1.18',
            'version' => '1.1.18.0',
            'reference' => 'f64dcbac2c52909e33f252a17f03b9ef66440419',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-commands',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        '10quality/wpmvc-core' => array(
            'pretty_version' => 'v3.1.18',
            'version' => '3.1.18.0',
            'reference' => '555e005bd71a16b5f143b316793711c3fb614e33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc-logger' => array(
            'pretty_version' => 'v2.0.x-dev',
            'version' => '2.0.9999999.9999999-dev',
            'reference' => '603fe1a295f6e12b7fea9ca7e4ce80db6f7270e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-logger',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc-mvc' => array(
            'pretty_version' => 'v2.1.15',
            'version' => '2.1.15.0',
            'reference' => 'f3d2a743fef3b219502c56de0a84c0cb96c1fde8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-mvc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        '10quality/wpmvc-phpfastcache' => array(
            'pretty_version' => 'v4.0.5',
            'version' => '4.0.5.0',
            'reference' => 'a97d06c83021ee1b254e366079d1427a87654ba3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../10quality/wpmvc-phpfastcache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'gettext/gettext' => array(
            'pretty_version' => 'v5.7.0',
            'version' => '5.7.0.0',
            'reference' => '8657e580747bb3baacccdcebe69cac094661e404',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gettext/gettext',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'gettext/js-scanner' => array(
            'pretty_version' => 'v1.1.2',
            'version' => '1.1.2.0',
            'reference' => '371bddca27b29eea5d553aade324c8e631ac3444',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gettext/js-scanner',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'gettext/languages' => array(
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => '4d61d67fe83a2ad85959fe6133d6d9ba7dddd1ab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gettext/languages',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'gettext/php-scanner' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'reference' => '989a2cffa1d0f43d13b14c83a50429119b5eb8e4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gettext/php-scanner',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'imangazaliev/didom' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '50fa6595d14f22c0c984efed5c818485cf548136',
            'type' => 'library',
            'install_path' => __DIR__ . '/../imangazaliev/didom',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-color' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'mck89/peast' => array(
            'pretty_version' => 'v1.16.2',
            'version' => '1.16.2.0',
            'reference' => '2791b08ffcc1862fe18eef85675da3aa58c406fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mck89/peast',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.19.1',
            'version' => '4.19.1.0',
            'reference' => '4e1b88d21c69391150ace211e9eaf05810858d0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-parallel-lint/php-console-color' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '7adfefd530aa2d7570ba87100a99e2483a543b88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-parallel-lint/php-console-color',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/log' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'fe0936ee26643249e916849d48e3a51d5f5e278b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
